# Telegram bot
TELEGRAM_BOT_TOKEN = 'INSERT_TELEGRAM_BOT_TOKEN_HERE'

# OpenAI API key
OPENAI_API_KEY = "INSERT_OPENAI_API_KEY_HERE"

# OpenAI models
GPT_MODEL = "gpt-3.5-turbo"
EMBEDDING_MODEL = "text-embedding-ada-002"
EMBEDDING_CTX_LENGTH = 8191
EMBEDDING_ENCODING = 'cl100k_base'

# Embeddings file path
EMBEDDINGS_FILE = "data/embeddings.csv"

# Google Bard API Key
GOOGLE_BARD_API_KEY = "INSERT_GOOGLE_API_KEY_HERE"
